name: deploy_frontend
on:
    push:
        branches: [main]
jobs:
    build-and-deploy_frontend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        env:
            working-directory: 'frontend'
            SSH_KEY: ${{secrets.SSH_KEY}}
            SERVER_IP: ${{secrets.SERVER_IP}}
        steps:
            - uses: actions/checkout@v2
            - run: ls
            - name: Use Node.js 16
              uses: actions/setup-node@v2
              working-directory: frontend
              with:
                  node-version: 16
                  cache: "npm"
                  cache-dependency-path: ./'frontend/package-lock.json'
            - run: ls
            - run: npm install
            - run: npm run build
            - run: mkdir ~/.ssh
            - run: 'echo "$SSH_KEY" >> ~/.ssh/github-action'
            - run: chmod 400 ~/.ssh/github-action
            - run: echo -e "Host tencent\n\tUser azus\n\tHostname "$SERVER_IP"\n\tIdentityFile ~/.ssh/github-action\n\tPreferredauthentications publickey\n\tStrictHostKeyChecking No" >> ~/.ssh/config
            # - run: rsync -e ssh ./build 80:~/home/contriTemp
            - run: scp -C -r ./build/* tencent:/home/azus/kds/
            # - run: ssh github-actions-tutorial "pm2 reload all"
    # build-and-deploy_mobile:
    #   runs-on: ubuntu-latest
    #   defaults:
    #     run:
    #       working-directory: ./frontend_mobile/
    #   env:
    #         SSH_KEY: ${{secrets.SSH_KEY}}
    #         SERVER_IP: ${{secrets.SERVER_IP}}
    #   steps:
    #       - uses: actions/checkout@v2
    #       - name: Use Node.js 16
    #         uses: actions/setup-node@v2
    #         with:
    #           node-version: 16
    #           cache: 'npm'
    #       - run: npm install
    #       - run: npm run build
    #       - run: mkdir ~/.ssh
    #       - run: 'echo "$SSH_KEY" >> ~/.ssh/github-action'
    #       - run: chmod 400 ~/.ssh/github-action
    #       - run: echo -e "Host tencent\n\tUser azus\n\tHostname "$SERVER_IP"\n\tIdentityFile ~/.ssh/github-action\n\tPreferredauthentications publickey\n\tStrictHostKeyChecking No" >> ~/.ssh/config
    #       - run: scp -C -r ./build/* tencent:/home/azus/kds_mobile/
    #       # - run: ssh github-actions-tutorial "pm2 reload all"
