name: deploy_master
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
          SSH_KEY: ${{secrets.SSH_KEY}}
          SERVER_IP: ${{secrets.SERVER_IP}}
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 16
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'npm'
        - run: cd fontend && npm install 
        - run: npm run build
        - run: mkdir ~/.ssh
        - run: 'echo "$SSH_KEY" >> ~/.ssh/github-action'
        - run: chmod 400 ~/.ssh/github-action
        - run: echo -e "Host tencent\n\tUser azus\n\tHostname "$SERVER_IP"\n\tIdentityFile ~/.ssh/github-action\n\tPreferredauthentications publickey\n\tStrictHostKeyChecking No" >> ~/.ssh/config
        # - run: rsync -e ssh ./build 80:~/home/contriTemp
        - run: scp -C -r ./build/* tencent:/home/azus/kds/
        - run: cd ../fontend_moile/ && npm install
        - run: npm run build
        - run: scp -C -r ./build/* tencent:/home/azus/kds_mobile/
        # - run: ssh github-actions-tutorial "pm2 reload all"
